name: Backup Git Repo

on:
  push:
    branches:
      - master

jobs:
  git-repo-backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: git-repo-backup
        uses: jenkins-zh/git-backup-actions@v0.0.1
        env:
          GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
          TARGET_GIT: "git@gitee.com:surenpi/surenpi.git"